* Test task
** Description
   Сделать веб-приложение - простой онлайн-чат на Rails 7 с использованием
   технологии Hotwire - Turbo.

   Что нужно сделать:

   - на главной странице должен быть список созданных чатов и возможность
     создать новый
   - любой пользователь может создать новый чат, при создании указать его
     название
   - любой пользователь может зайти в любой чат, увидеть историю переписки и
     отправить своё сообщение
   - после отправки сообщения у всех пользователей, у которых открыт чат, должно
     появиться новое сообщение в чате
   - при получении нового сообщения должно появиться уведомление со звуком, в
     котором будет название чата и текст сообщения (дизайн и расположение - по
     желанию)

   Что будет оцениваться:

   - организация кода, использование методов и библиотек
   - количество кода - чем меньше, тем лучше, по максимуму используйте дефолтные
     паттерны RoR и Hotwire
   - простота и читаемость кода
   - общий результат с точки зрения пользователя
   - скорость выполнения
** Docs
   - https://www.youtube.com/watch?v=eKY-QES1XQQ
   - https://www.hotrails.dev/turbo-rails/turbo-streams
** Tasks
   - [X] Rooms on main
   - [X] Create room
   - [X] Messages history
   - [X] Send message
   - [X] Chat live update
   - [ ] Toast
   - [ ] Sound
** 28/01/2023
*** 19:32:11
    Hotwire: The Demo.

    Пока обойду Redis (=./bin/rails turbo:install:redis=), до тех пор пока не
    наткнусь на необходимость.
*** 23:07:34
    rails new ka-test --css bootstrap

    Дальше по сценарию.
** 29/01/2023
*** 03:36:25
    Комнаты создаются, сообщения отправляются. Довести до конечного состояния.
*** 06:05:59
    Используется Turbo Stream, только без Redis не шлются сообщения при работе
    из консоли.

    Теперь наверное надо добавить пользователей.
